import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { AppWrapper } from '@/components/context/appWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang='ua'>
            <head />
            <body className={inter.className}>
                <AppWrapper>
                    <ThemeProvider
                        attribute='class'
                        defaultTheme='system'
                        enableSystem
                        disableTransitionOnChange>
                        {children}
                    </ThemeProvider>
                </AppWrapper>
            </body>
        </html>
    )
}
